services:
  - type: web
    name: kafela-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kafela_rest_main.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-n&iyrx2ve5b+v23)h_w4l0#x=as!ua#hoxqoejxe!97=e%5@2!
      - key: DATABASE_URL
        fromDatabase:
          name: kafela_db
          property: connectionString

databases:
  - name: kafela_db
