
### 🔐 Register a new user
POST http://localhost:8000/api/register/
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "username": "user2",
  "password": "user1212",
  "confirm_password": "user1212",
  "full_name": "User2 Khan",
  "institution": "UIU",
  "user_type": "FREEMIUM"
}



### 🔐 User Login to get JWT Token

POST http://localhost:8000/api/login/
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "user1212"
}



### 🔐 Admin Login to get JWT Token

POST http://localhost:8000/api/login/
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "admin1212"
}



### ♻️ Refresh token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDExMzY5MywiaWF0IjoxNzU0MDI3MjkzLCJqdGkiOiI5ZjE1MjkxOWFjYzA0ZDJiODIwNzg3YzhmZWQxNTc0MiIsInVzZXJfaWQiOiI0In0.iNY5belplRzGF7U56jboSf7sPpk7_p2oPx8aZpf616g"
}



### 📚 Get all books (no auth required if public)

GET http://localhost:8000/api/books/
Content-Type: application/json



### ➕ Add a new book (admin only)
POST http://127.0.0.1:8000/api/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzOTg0Njg5LCJpYXQiOjE3NTM5ODQzODksImp0aSI6IjQ3YTM3NDAxMzA2YTQ5NzNiYTdhZDlkNGUzYTIxYzg2IiwidXNlcl9pZCI6IjIifQ.8Uhgq5CHZ2EIMRFXp1xxePdwjrJBZT_P0CFGnRF1ppA
Content-Type: application/json

{
  "title": "Tasauf o Atto-shuddhi",
  "author": "Mufti Taqi Usmani",
  "description": "Treatment of any sick Heart(Qalb)",
  "is_available": true,
  "total_pages": 290,
  "category_id": 2
}



### 🔎 Get a single book by ID
GET http://127.0.0.1:8000/api/books/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDI2NTcwLCJpYXQiOjE3NTQwMjYyNzAsImp0aSI6ImIwMjU2NjQ4OTNhNzQxZTQ5YjJjM2YzY2U4N2JkZGQ4IiwidXNlcl9pZCI6IjQifQ.oSS3AFdcnNVyKdPTQwpxxL24ApDp45EZj7HI9ARUGPM



### 📥 Create a Book Request (user only)
POST http://127.0.0.1:8000/api/book_requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDI2NTcwLCJpYXQiOjE3NTQwMjYyNzAsImp0aSI6ImIwMjU2NjQ4OTNhNzQxZTQ5YjJjM2YzY2U4N2JkZGQ4IiwidXNlcl9pZCI6IjQifQ.oSS3AFdcnNVyKdPTQwpxxL24ApDp45EZj7HI9ARUGPM
Content-Type: application/json

{
  "book": 2
}



### 📄 Get all book requests (own for user / all for admin)
GET http://127.0.0.1:8000/api/book_requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NTQ5MzkwLCJpYXQiOjE3NTQ1NDkwOTAsImp0aSI6ImY2ZjQ5N2NjZjg1MTQzMmQ5MzUzNzE3ZGFmYzFkYmFjIiwidXNlcl9pZCI6IjIifQ.8AColz74k2b-i9zCPr05aEURUY9iqe09jAEMm1N0Rpc


### 🔁 Get book request by ID
GET http://127.0.0.1:8000/api/book_requests/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDI2ODgzLCJpYXQiOjE3NTQwMjY1ODMsImp0aSI6IjVhNGI1OTUyYmEyZjQzZWRiZDE5MDcxYjE5Y2VlOGJjIiwidXNlcl9pZCI6IjQifQ._X37toVLbiCUpsw1Sj5317cgMrtk89QhTtnFDkKT7zw



### ✍️ Post a review for a book (book_id = select)
POST http://127.0.0.1:8000/api/books/2/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDI3NjExLCJpYXQiOjE3NTQwMjczMTEsImp0aSI6IjRmYmQ2OTYxYWNjZjRjNTA5MTUzMTIxNDYzMmY1Nzk5IiwidXNlcl9pZCI6IjQifQ.a16_4YBdF6Noap86WVIeIfjiqA3bxzRk-652b-BCuL0
Content-Type: application/json

{
  "rating": 9,
  "comment": "This book just changed my mind, mindset and life"
}



### 📖 Get reviews for a specific book
GET http://127.0.0.1:8000/api/books/2/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDI3OTI3LCJpYXQiOjE3NTQwMjc2MjcsImp0aSI6IjQzMDVkNWFmNzVmNTQ4ZWQ5Mjg4YmY4Y2NmZWM4NTc4IiwidXNlcl9pZCI6IjQifQ.EOxyNM6vALIIGIuZ8m4LmUa0PbwKVDZeH0h4guIx84k



### 🎲 Get random reviews
GET http://127.0.0.1:8000/api/random_reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NTQ5MzkwLCJpYXQiOjE3NTQ1NDkwOTAsImp0aSI6ImY2ZjQ5N2NjZjg1MTQzMmQ5MzUzNzE3ZGFmYzFkYmFjIiwidXNlcl9pZCI6IjIifQ.8AColz74k2b-i9zCPr05aEURUY9iqe09jAEMm1N0Rpc



### 📁 Add new category (Admin Only)
POST http://127.0.0.1:8000/api/categories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NTQ5NzMwLCJpYXQiOjE3NTQ1NDk0MzAsImp0aSI6ImU1MDg2YWEzMzRhMzRjYmQ4ODNiMjIwZTRmNTY0MGIyIiwidXNlcl9pZCI6IjIifQ.1ZpMG9N02bOzLHpDxOqR8Ox1Yq7RfQS1_CL_GI4ZxuM

{
  "category": "WorldViews",
  "description": "Developing real world viewpoints",
}



### 📁 Get all categories
GET http://127.0.0.1:8000/api/categories/



### 👤 User Dashboard
GET http://127.0.0.1:8000/api/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDQyNzM3LCJpYXQiOjE3NTQwNDI0MzcsImp0aSI6IjBkODc3N2MyZTM3NTRhMGJiMjljZDI4YzdkMWYyNTljIiwidXNlcl9pZCI6IjQifQ.8aa7I0_4H951t1NEyTqXa_0ONEXsI-QqL9_D0o3heps



### 🛠 Admin Dashboard
GET http://127.0.0.1:8000/api/admin/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MDQyNjc3LCJpYXQiOjE3NTQwNDIzNzcsImp0aSI6ImRmNTIzNWY2MWE4ODRhNDdhM2M5Zjg0OWU2NTNiMmU3IiwidXNlcl9pZCI6IjIifQ._3UL0_D3bJYPLImv3lI76RBEAaPof9mv48Vn-TjlYEU



### 🔍 Search books by title/auther/description
GET http://127.0.0.1:8000/api/books/?search=django



### 🔍 Filter books by category name (case-insensitive)
GET http://127.0.0.1:8000/api/books/?category=Ethics



### 🔍 Filter by category + availability
GET http://127.0.0.1:8000/api/books/?category=Programming&is_available=true

